spring:
  application:
    name: alert-stream-service
  
  datasource:
    url: jdbc:postgresql://localhost:5432/alert_news
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
  
  websocket:
    max-text-message-size: 8192
    max-binary-message-size: 8192

server:
  port: 8080
  servlet:
    context-path: /

# WebSocket 설정
websocket:
  endpoint: /ws/news
  max-connections-per-customer: 1

# 큐 설정
queue:
  capacity: 1000
  poll-timeout: 1000

# 고객사 인증 설정
customer:
  token:
    expiry-hours: 24

# 로깅 설정
logging:
  level:
    com.alert.news: DEBUG
    org.springframework.web.socket: DEBUG
    org.springframework.messaging: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

# Actuator 설정
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true
